### ISSUE TITLE
Improve initialization of a page or a component

### ISSUE THREAD

**Issue by opensource21** [elisarver/selophane#16]
I was a little bit confused why in the test-example we get the page with 

```
    public static FormTestObject initialize(WebDriver driver) {
        return ElementFactory.initElements(driver, FormTestObject.class);
    }
```
?

It implies that someone could instantiate the Page without call `initElements`, which seems like a bad idea.

I think it would be smarter to put into the constructor 
`ElementFactory.initElements(driver, this);`

If this correct, I wonder why there is no base-class ` Component`, which encapsulate the `SearchContext` and do the initialization.

I could make the refactoring if the idea is accepted.

**Comment by elisarver** [comment]
This was following the original Page object 'pattern' as implemented by WebDriver examples. I was not interested in coming up with a 'new' way of doing it at the time, as I was using a base page that did this in one place, and inheriting from it.

That just left me with having to remember to call super() before the rest of the initialization.

**Comment by opensource21** [comment]
If there was no Default-Constructor you are forced to call it, but of course you aren't force to use the base-class. But if I understand you correct, you would prefer to have such a base-class out-side of selophane?

**Comment by elisarver** [comment]
Right, the point of Selophane is not to provide the base class, because I've found that varies even within a company using WebDriver, so I don't want

**Comment by opensource21** [comment]
Thanks for clarify.
