### ISSUE TITLE
Method to get all css-classes

### ISSUE THREAD

**Issue by opensource21** [elisarver/selophane#19]
In many elements I wan't to figured out something about the state of an element. For example the MenuItem should be highlighted. So I want to check the existance of the css-class "active".
I wrote a method

    /**
     * Get a list of name of classes, which stands in the attribut class.
     */
    protected final List<String> getClasses() {
        final String classAttribute = this.getAttribute("class");
        if (StringUtils.isEmpty(classAttribute)) {
            return new ArrayList<>();
        }
        final String[] primitiveList = classAttribute.split(" ");
        return Arrays.asList(primitiveList);
    }

which I added to ElementImpl. Is it possible to get this into selophane or how would you solve it?

**Comment by elisarver** [comment]
I'd solve it in about the same way you have done so. If I were using Guava,
I'd use:

Splitter.on(CharMatcher.WHITESPACE).omitEmptyStrings().trimResults().splitToList(this.getAttribute("class")
)

Then again, I love Guava, and use it every time I have a chance.

I don't know whether it belongs in Selophane or not, given the original
goals of the project. I've been pretty resistant thus far to expansions of
its core design.

**Comment by opensource21** [comment]
Even with Guava (which shouldn't become part of selophane), I think it's a lot of code. But I can understand your concerns. In jtaf-extwebdriver I'm unhappy with the large number of methods each interface has. Even here I found it not easy to find the methods a widget provides. On the other hand a `CSSHelper`-class with `getClasses(WebElememt e)` doesn't look very clean. It's your project so you can decide. I can't guarantee that I don't find the next handy method in the next month.

**Comment by opensource21** [comment]
I think it's better to don't put it into selophane, otherwise we will get discussions how to handle the case that there is no class-attribute. I prefer an empty list, you a NullPointerException.

**Comment by elisarver** [comment]
Splitter guarantees an empty list for a non-empty string. Also, I strive
for nonnull functionality, so maybe I should take another look and annotate
selophane with nullity annotations and refactor.

**Comment by opensource21** [comment]
I made a test and got a NullPointer for `Splitter.on(CharMatcher.WHITESPACE).omitEmptyStrings().trimResults()
    .splitToList(null)`;
Anyway do you have #20 on your list?

**Comment by elisarver** [comment]
I just merged your pull request. Thank you!
