### ISSUE TITLE
Unable to extend widgets and reference their methods

### ISSUE THREAD

**Issue by EllaVader** [elisarver/selophane#24]
I have added some additional functionality to the Table implementation to allow for sorting headers.
I felt it wasn't necessary to put it in the interface since not all tables have sortable header.  However when initializing the Table object using initElements, I can't cast or call the implementing classes method.  Getting ClassCastException

    @FindBy(id = "table2")
    Table sortableTable;
    
    @Test
    public void testClickColumnToSort() {
        TableTest testPage = ElementFactory.initElements(driver, TableTest.class);
        //Note: sortableTable is interface, but we need the implementations method "clickColumnToSort,
        //so trying to cast it throws ClassCastException
        TableImpl base = (TableImpl) testPage.sortableTable;
        base.clickColumnToSort(1);
    }

**Comment by EllaVader** [comment]
I provided code example in Pull request.  Can you grab it and try it out and take a look?

**Comment by opensource21** [comment]
Hi Ella, this can't work. Because you always get a proxy around your element. So you must create your own interface and implemtation. I changed the implementation #23 where this isn't necessary any more.
I integrate the whole stuff into my library [webtest](https://github.com/opensource21/webtest).

**Comment by EllaVader** [comment]
HI opensource21 -- sorry for the delay in getting back to you.  So do you mean that your implementation removes the necessity of having to create an interface and implementation class for each webelement type?  So how does your implementation do it?  Do you have an example of this or provide which class(es) you changed to achieve this?

**Comment by opensource21** [comment]
Sorry but I don't know, what for information I could add to the pull-request #23. There you can find a description of what I have done and can find the code changes. If you want to see an example which use this possibility I must disappoint you, because I found it useful to have the interfaces for each WebElement. So I didn't try it out.
