### ISSUE TITLE
Element returns different element memory from driver.findElement(By)

### ISSUE THREAD

**Issue by williamrussellajb** [elisarver/selophane#29]
When an element is created using the factory, it is a different element from driver.findBy. 

Example code:
    @FindBy(xpath = "//xx")
    Element myElement

Init the driver page using the factory and navigate to your element. 

This should return true:
myElement.equals(driver.switchTo().activeElement());

However, its false. If I use this example in normal selenium  it works. 

This  causes problems when executing scripts.

**Comment by elisarver** [comment]
Can you provide a pom and java test file reproducing the issue?

**Comment by williamrussellajb** [comment]
Which platform are you on?

**Comment by elisarver** [comment]
I'm on Mac, but anything will do; Java is Java as long as you don't involve os specific stuff or filesystems.

**Comment by williamrussellajb** [comment]
I have added two projects here: 
https://github.com/williamrussellajb/example.git

The example project is very simple, just two classes. A page, and a test example. 
I added the exact same example inside selophane.  

Please look at both packages in both projects.
com.example.page
com.example.test


The assertion fails when using selophane.

**Comment by williamrussellajb** [comment]
Thank you so much for this as well, I cannot see any other way to use selenium anymore. Your project removes 99% of the boilerplate code inside page objects.

**Comment by williamrussellajb** [comment]
ok-added it also, I had to rename selophane to selophane2. should be working now.

**Comment by elisarver** [comment]
Ah, I see what the issue is. 
1) Instead of WebElement in your google class, use Element from selophane library. 
2) Then change your test to call getWrappedElement on that field to get an equivalent element that selenium can use for comparison.

**Comment by williamrussellajb** [comment]
Thank you Elisarver!

You're right! 

In case anyone else faces this issue, here is your answer in code.

```
Assert.assertTrue(googlePage.searchBox.getWrappedElement().equals(driver.switchTo().activeElement()));
```

**Comment by elisarver** [comment]
Glad it worked out.
