### ISSUE TITLE
Can we avoid to create an interface for new Element?

### ISSUE THREAD

**Issue by thibaut-sticky** [elisarver/selophane#8]
Hi,

First, I want to thank you for your project. It was exactly what I'm looking for since few month. It's seems crazy that features as modify the FindBy behavior are not explained or implemented by Selenium team.

I tested your work, and it works pretty fine.

Here my question. I found verbose the fact to create an interface for each new element I created. Do you think it will be possible to avoid it?

**Comment by elisarver** [comment]
Everything has to be a descendant of WebElement, which is an interface class. This allows the annotation processor to have a “hook” by which they can apply the sub-classes. They, likewise, are represented by an interface for consistency. The implementation of those interfaces guarantees there are no surprise classes.

Please let me know if that answers your question.

**Comment by thibaut-sticky** [comment]
Thank for the quick answer. Clearly, yes, everything should be descendant of WebElement. But if I understood well, in

```JAVA
public class TextInputImpl extends ElementImpl implements TextInput
```
the interface `TextInput` is here just for consistency, not for technical reason?
I tried in my Page Object to declare a member as follow: 

```JAVA
    @FindBy(css = "#brand-element input[name=brand_name]")
    private TextInputImpl brandFilter;
```

but exception is raised in `getWrappedClass`,  *Apply @ImplementedBy interface to your Interface if you want to extend* because of course `TextInputImpl` does not have `@ImplementedBy`.

In my opinion, forcing to create an other interface for each element is painful, there is already `Element`. Extends `ElementImpl` should be enough to check.

**Comment by elisarver** [comment]
Without the annotation we cannot check the contract of the implementation.

Without the separation of the Interface and Impl we cannot assign a descendant of WebElement (an Interface) which Selenium requires.

So without these things, Selenium itself cannot accept the WebElements that we create.
